# Generated by Django 4.2 on 2023-05-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_comment_customer'),
        ('account', '0002_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cupons',
            field=models.ManyToManyField(to='shop.cupon', verbose_name='Доступные купоны'),
        ),
        migrations.AddField(
            model_name='account',
            name='favorite_products',
            field=models.ManyToManyField(related_name='account', to='shop.product', verbose_name='Избранные продукты'),
        ),
    ]
