# Generated by Django 4.2 on 2023-05-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_comment_customer'),
        ('account', '0003_account_cupons_account_favorite_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activated_cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_activated', to='shop.cupon', verbose_name='Активированный купон'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cupons',
            field=models.ManyToManyField(related_name='accounts', to='shop.cupon', verbose_name='Доступные купоны'),
        ),
    ]
