# Generated by Django 4.2 on 2023-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_cupons_alter_account_favorite_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar_img',
            field=models.ImageField(blank=True, upload_to='account_avatar/title/%Y/%m/%d'),
        ),
    ]
