# Generated by Django 4.2 on 2023-05-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin')], default='U', max_length=1, verbose_name='Автор сообщения'),
        ),
    ]
