# Generated by Django 4.2 on 2023-04-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="price_old",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
