# Generated by Django 4.2 on 2023-04-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_product_price_old"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Имя img", max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="products/slider/%Y/%m/%d"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_title",
            field=models.ImageField(blank=True, upload_to="products/title/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_slider",
            field=models.ManyToManyField(to="shop.productimageitem"),
        ),
    ]
