# Generated by Django 4.2 on 2023-04-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_productimageitem_remove_product_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimageitem",
            options={
                "verbose_name": "Фото продуктов на слайдер",
                "verbose_name_plural": "Фотографии продуктов на слайдер",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image_slider",
            field=models.ManyToManyField(blank=True, to="shop.productimageitem"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Цена в данный момент", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_old",
            field=models.DecimalField(
                decimal_places=2, help_text="Цена до изменения", max_digits=10
            ),
        ),
    ]
