# Generated by Django 4.2 on 2023-05-03 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'Отзыв о товаре', 'verbose_name_plural': 'Отзывы о товаре'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='comment',
            name='product_score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка продукта'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
