# Generated by Django 4.2 on 2023-05-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_commentimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentimage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
