# Generated by Django 4.2 on 2023-05-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, help_text='введите ваш город', max_length=100, verbose_name='город'),
        ),
    ]
